# Generated by Django 5.1.3 on 2024-11-21 18:14

from django.db import migrations
from django.conf import settings
from django.utils import timezone
from datetime import datetime

def build_datetime(datetime_str):
    return timezone.make_aware(datetime.strptime(datetime_str, settings.DATETIME_MASK))

def create_default_sales_channels(apps, schema_editor):
    SaleChannel = apps.get_model('api', 'SaleChannel')

    default_categories = [
        "marketplace",
        "loja",
    ]

    for name in default_categories:
        SaleChannel.objects.get_or_create(name=name)

def create_init_sales_records(apps, schema_editor):
    Sale = apps.get_model('api', 'Sale')
    SaleChannel = apps.get_model('api', 'SaleChannel')

    mkt_plac_categ = SaleChannel.objects.get(name="marketplace")
    loja_categ = SaleChannel.objects.get(name="loja")

    init_records = [
        {"date": build_datetime("24/01/2024 12:45:30"), "price": "150.00", "cost": "45.50", "state": "CE", "sale_channel": mkt_plac_categ},
        {"date": build_datetime("26/07/2024 09:38:01"), "price": "259.99", "cost": "75.01", "state": "CE", "sale_channel": loja_categ},
        {"date": build_datetime("08/09/2024 00:00:15"), "price": "781.00", "cost": "600.00", "state": "SP", "sale_channel": loja_categ},
        {"date": build_datetime("15/09/2024 16:00:59"), "price": "45.00", "cost": "9.00", "state": "RJ", "sale_channel": mkt_plac_categ},
        {"date": build_datetime("30/09/2024 07:30:34"), "price": "1150.00", "cost": "900.00", "state": "RJ", "sale_channel": mkt_plac_categ},
        {"date": build_datetime("30/09/2024 12:23:35"), "price": "9.99", "cost": "9.00", "state": "BA", "sale_channel": loja_categ},
    ]

    for record in init_records:
        Sale.objects.get_or_create(**record)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_sales_channels),
        migrations.RunPython(create_init_sales_records),
    ]